package com.health.insurance.medicalhistory.model.utility.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldDefaults;

@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@FieldDefaults(level = AccessLevel.PRIVATE)
@Entity
@Table(name = "lab_tests")
public class LabTests {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @JsonIgnore
    Integer id;
    Integer labTestsId;
    String sugarInUrine;
    String bilirubinInUrine;
    String ketonesInUrine;
    String proteinInUrine;
    String rbcBloodCountInUrine;
    String resultOfTMT;
    String resultOfDobutamineStressECHO;
    String resultOfStressThallium;
    String resultOfCTFindings;
    String resultOfChestXRay;
    String resultOfEcho;
    String resultOfECG;
    String resultOfUSGAbdomen;
    Boolean otherMedicalReports;
    String crystalsInUrine;
    String rbcWBCCastsInUrine;
    String granularWaxyCasts;
    Double wbcPlusCellsInUrine;
    Double rbcPerHPF;
    Double countOfRBC;
    Double upperCountOfRBC;
    Double lowerCountOfRBC;
    Double pcvHematocrit;
    Double upperCountOfPCVHematocrit;
    Double lowerCountOfPCVHematocrit;
    Double countOfMCV;
    Double upperCountOfMCV;
    Double lowerCountOfMCV;
    Double countOfMCH;
    Double upperCountOfMCH;
    Double lowerCountOfMCH;
    Double countOfMCHC;
    Double upperCountOfMCHC;
    Double lowerCountOfMCHC;
    Double valueOfTSH;
    Double upperValueOfTSH;
    Double lowerValueOfTSH;
    Double valueOfTLC;
    Double upperValueOfTLC;
    Double lowerValueOfTLC;
    Double valueOfNeutrophil;
    Double upperValueOfNeutrophil;
    Double lowerValueOfNeutrophil;
    Double valueOfEsoinophil;
    Double upperValueOfEsoinophil;
    Double lowerValueOfEsoinophil;
    Double valueOfBasophil;
    Double upperValueOfBasophil;
    Double lowerValueOfBasophil;
    Double valueOfMonocyte;
    Double upperValueOfMonocyte;
    Double lowerValueOfMonocyte;
    Double valueOfLymphocyte;
    Double upperValueOfLymphocyte;
    Double lowerValueOfLymphocyte;
    Double countOfPlatelet;
    Double upperCountOfPlatelet;
    Double lowerCountOfPlatelet;
    Double valueOfESR;
    Double upperValueOfESR;
    Double lowerValueOfESR;
    Double valueOfFBS;
    Double upperValueOfFBS;
    Double lowerValueOfFBS;
    Double valueOfHbA1C;
    Double upperValueOfHbA1C;
    Double lowerValueOfHbA1C;
    Double valueOfSerumCreatinineRFT;
    Double upperValueOfSerumCreatinineRFT;
    Double lowerValueOfSerumCreatinineRFT;
    Double amountOfUricAcid;
    Double upperAmountOfUricAcid;
    Double lowerAmountOfUricAcid;
    Double valueOfSGOTAST;
    Double upperValueOfSGOTAST;
    Double lowerValueOfSGOTAST;
    Double valueOfSGPTALT;
    Double upperValueOfSGPTALT;
    Double lowerValueOfSGPTALT;
    Double ratioBetweenSGOTAndSGPT;
    Double valueOfBUN;
    Double upperValueOfBUN;
    Double lowerValueOfBUN;
    Double valueOfNA;
    Double upperValueOfNA;
    Double lowerValueOfNA;
    Double valueOfK;
    Double upperValueOfK;
    Double lowerValueOfK;
    Double valueOfCA;
    Double upperValueOfCA;
    Double lowerValueOfCA;
    Double valueOfPO4;
    Double upperValueOfPO4;
    Double lowerValueOfPO4;
    Double valueOfCI;
    Double upperValueOfCI;
    Double lowerValueOfCI;
    Double valueOfHCO3;
    Double upperValueOfHCO3;
    Double lowerValueOfHCO3;
    Double valueOfGGT;
    Double upperValueOfGGT;
    Double lowerValueOfGGT;
    Double valueOfALP;
    Double upperValueOfALP;
    Double lowerValueOfALP;
    Double valueOfTotalBilirubin;
    Double upperValueOfTotalBilirubin;
    Double lowerValueOfTotalBilirubin;
    Double valueOfSerumAlbumin;
    Double upperValueOfSerumAlbumin;
    Double lowerValueOfSerumAlbumin;
    Double valueOfUrineMicroAlbumin;
    Double upperValueOfUrineMicroAlbumin;
    Double lowerValueOfUrineMicroAlbumin;
    Double valueOfTotalProtein;
    Double upperValueOfTotalProtein;
    Double lowerValueOfTotalProtein;
    Double valueOfPSA;
    Double upperValueOfPSA;
    Double lowerValueOfPSA;
    Double valueOfTC;
    Double upperValueOfTC;
    Double lowerValueOfTC;
    Double valueOfLDL;
    Double upperValueOfLDL;
    Double lowerValueOfLDL;
    Double heartRate;
    Double valueOfHDL;
    Double valueOfHB;
    Integer percentageOfLVEF;

    public LabTests(final LabTests labTests) {
        this.setLabTestsId(labTests.getLabTestsId());
        this.setSugarInUrine(labTests.getSugarInUrine());
        this.setBilirubinInUrine(labTests.getBilirubinInUrine());
        this.setKetonesInUrine(labTests.getKetonesInUrine());
        this.setProteinInUrine(labTests.getProteinInUrine());
        this.setRbcBloodCountInUrine(labTests.getRbcBloodCountInUrine());
        this.setResultOfTMT(labTests.getResultOfTMT());
        this.setResultOfDobutamineStressECHO(labTests.getResultOfDobutamineStressECHO());
        this.setResultOfStressThallium(labTests.getResultOfStressThallium());
        this.setResultOfCTFindings(labTests.getResultOfCTFindings());
        this.setResultOfChestXRay(labTests.getResultOfChestXRay());
        this.setResultOfEcho(labTests.getResultOfEcho());
        this.setResultOfECG(labTests.getResultOfECG());
        this.setResultOfUSGAbdomen(labTests.getResultOfUSGAbdomen());
        this.setOtherMedicalReports(labTests.getOtherMedicalReports());
        this.setCrystalsInUrine(labTests.getCrystalsInUrine());
        this.setRbcWBCCastsInUrine(labTests.getRbcWBCCastsInUrine());
        this.setGranularWaxyCasts(labTests.getGranularWaxyCasts());
        this.setWbcPlusCellsInUrine(labTests.getWbcPlusCellsInUrine());
        this.setRbcPerHPF(labTests.getRbcPerHPF());
        this.setCountOfRBC(labTests.getCountOfRBC());
        this.setUpperCountOfRBC(labTests.getUpperCountOfRBC());
        this.setLowerCountOfRBC(labTests.getLowerCountOfRBC());
        this.setPcvHematocrit(labTests.getPcvHematocrit());
        this.setUpperCountOfPCVHematocrit(labTests.getUpperCountOfPCVHematocrit());
        this.setLowerCountOfPCVHematocrit(labTests.getLowerCountOfPCVHematocrit());
        this.setCountOfMCV(labTests.getCountOfMCV());
        this.setUpperCountOfMCV(labTests.getUpperCountOfMCV());
        this.setLowerCountOfMCV(labTests.getLowerCountOfMCV());
        this.setCountOfMCH(labTests.getCountOfMCH());
        this.setUpperCountOfMCH(labTests.getUpperCountOfMCH());
        this.setLowerCountOfMCH(labTests.getLowerCountOfMCH());
        this.setCountOfMCHC(labTests.getCountOfMCHC());
        this.setUpperCountOfMCHC(labTests.getUpperCountOfMCHC());
        this.setLowerCountOfMCHC(labTests.getLowerCountOfMCHC());
        this.setValueOfTSH(labTests.getValueOfTSH());
        this.setUpperValueOfTSH(labTests.getUpperValueOfTSH());
        this.setLowerValueOfTSH(labTests.getLowerValueOfTSH());
        this.setValueOfTLC(labTests.getValueOfTLC());
        this.setUpperValueOfTLC(labTests.getUpperValueOfTLC());
        this.setLowerValueOfTLC(labTests.getLowerValueOfTLC());
        this.setValueOfNeutrophil(labTests.getValueOfNeutrophil());
        this.setUpperValueOfNeutrophil(labTests.getUpperValueOfNeutrophil());
        this.setLowerValueOfNeutrophil(labTests.getLowerValueOfNeutrophil());
        this.setValueOfEsoinophil(labTests.getValueOfEsoinophil());
        this.setUpperValueOfEsoinophil(labTests.getUpperValueOfEsoinophil());
        this.setLowerValueOfEsoinophil(labTests.getLowerValueOfEsoinophil());
        this.setValueOfBasophil(labTests.getValueOfBasophil());
        this.setUpperValueOfBasophil(labTests.getUpperValueOfBasophil());
        this.setLowerValueOfBasophil(labTests.getLowerValueOfBasophil());
        this.setValueOfMonocyte(labTests.getValueOfMonocyte());
        this.setUpperValueOfMonocyte(labTests.getUpperValueOfMonocyte());
        this.setLowerValueOfMonocyte(labTests.getLowerValueOfMonocyte());
        this.setValueOfLymphocyte(labTests.getValueOfLymphocyte());
        this.setUpperValueOfLymphocyte(labTests.getUpperValueOfLymphocyte());
        this.setLowerValueOfLymphocyte(labTests.getLowerValueOfLymphocyte());
        this.setCountOfPlatelet(labTests.getCountOfPlatelet());
        this.setUpperCountOfPlatelet(labTests.getUpperCountOfPlatelet());
        this.setLowerCountOfPlatelet(labTests.getLowerCountOfPlatelet());
        this.setValueOfESR(labTests.getValueOfESR());
        this.setUpperValueOfESR(labTests.getUpperValueOfESR());
        this.setLowerValueOfESR(labTests.getLowerValueOfESR());
        this.setValueOfFBS(labTests.getValueOfFBS());
        this.setUpperValueOfFBS(labTests.getUpperValueOfFBS());
        this.setLowerValueOfFBS(labTests.getLowerValueOfFBS());
        this.setValueOfHbA1C(labTests.getValueOfHbA1C());
        this.setUpperValueOfHbA1C(labTests.getUpperValueOfHbA1C());
        this.setLowerValueOfHbA1C(labTests.getLowerValueOfHbA1C());
        this.setValueOfSerumCreatinineRFT(labTests.getValueOfSerumCreatinineRFT());
        this.setUpperValueOfSerumCreatinineRFT(labTests.getUpperValueOfSerumCreatinineRFT());
        this.setLowerValueOfSerumCreatinineRFT(labTests.getLowerValueOfSerumCreatinineRFT());
        this.setAmountOfUricAcid(labTests.getAmountOfUricAcid());
        this.setUpperAmountOfUricAcid(labTests.getUpperAmountOfUricAcid());
        this.setLowerAmountOfUricAcid(labTests.getLowerAmountOfUricAcid());
        this.setValueOfSGOTAST(labTests.getValueOfSGOTAST());
        this.setUpperValueOfSGOTAST(labTests.getUpperValueOfSGOTAST());
        this.setLowerValueOfSGOTAST(labTests.getLowerValueOfSGOTAST());
        this.setValueOfSGPTALT(labTests.getValueOfSGPTALT());
        this.setUpperValueOfSGPTALT(labTests.getUpperValueOfSGPTALT());
        this.setLowerValueOfSGPTALT(labTests.getLowerValueOfSGPTALT());
        this.setRatioBetweenSGOTAndSGPT(labTests.getRatioBetweenSGOTAndSGPT());
        this.setValueOfBUN(labTests.getValueOfBUN());
        this.setUpperValueOfBUN(labTests.getUpperValueOfBUN());
        this.setLowerValueOfBUN(labTests.getLowerValueOfBUN());
        this.setValueOfNA(labTests.getValueOfNA());
        this.setUpperValueOfNA(labTests.getUpperValueOfNA());
        this.setLowerValueOfNA(labTests.getLowerValueOfNA());
        this.setValueOfK(labTests.getValueOfK());
        this.setUpperValueOfK(labTests.getUpperValueOfK());
        this.setLowerValueOfK(labTests.getLowerValueOfK());
        this.setValueOfCA(labTests.getValueOfCA());
        this.setUpperValueOfCA(labTests.getUpperValueOfCA());
        this.setLowerValueOfCA(labTests.getLowerValueOfCA());
        this.setValueOfPO4(labTests.getValueOfPO4());
        this.setUpperValueOfPO4(labTests.getUpperValueOfPO4());
        this.setLowerValueOfPO4(labTests.getLowerValueOfPO4());
        this.setValueOfCI(labTests.getValueOfCI());
        this.setUpperValueOfCI(labTests.getUpperValueOfCI());
        this.setLowerValueOfCI(labTests.getLowerValueOfCI());
        this.setValueOfHCO3(labTests.getValueOfHCO3());
        this.setUpperValueOfHCO3(labTests.getUpperValueOfHCO3());
        this.setLowerValueOfHCO3(labTests.getLowerValueOfHCO3());
        this.setValueOfGGT(labTests.getValueOfGGT());
        this.setUpperValueOfGGT(labTests.getUpperValueOfGGT());
        this.setLowerValueOfGGT(labTests.getLowerValueOfGGT());
        this.setValueOfALP(labTests.getValueOfALP());
        this.setUpperValueOfALP(labTests.getUpperValueOfALP());
        this.setLowerValueOfALP(labTests.getLowerValueOfALP());
        this.setValueOfTotalBilirubin(labTests.getValueOfTotalBilirubin());
        this.setUpperValueOfTotalBilirubin(labTests.getUpperValueOfTotalBilirubin());
        this.setLowerValueOfTotalBilirubin(labTests.getLowerValueOfTotalBilirubin());
        this.setValueOfSerumAlbumin(labTests.getValueOfSerumAlbumin());
        this.setUpperValueOfSerumAlbumin(labTests.getUpperValueOfSerumAlbumin());
        this.setLowerValueOfSerumAlbumin(labTests.getLowerValueOfSerumAlbumin());
        this.setValueOfUrineMicroAlbumin(labTests.getValueOfUrineMicroAlbumin());
        this.setUpperValueOfUrineMicroAlbumin(labTests.getUpperValueOfUrineMicroAlbumin());
        this.setLowerValueOfUrineMicroAlbumin(labTests.getLowerValueOfUrineMicroAlbumin());
        this.setValueOfTotalProtein(labTests.getValueOfTotalProtein());
        this.setUpperValueOfTotalProtein(labTests.getUpperValueOfTotalProtein());
        this.setLowerValueOfTotalProtein(labTests.getLowerValueOfTotalProtein());
        this.setValueOfPSA(labTests.getValueOfPSA());
        this.setUpperValueOfPSA(labTests.getUpperValueOfPSA());
        this.setLowerValueOfPSA(labTests.getLowerValueOfPSA());
        this.setValueOfTC(labTests.getValueOfTC());
        this.setUpperValueOfTC(labTests.getUpperValueOfTC());
        this.setLowerValueOfTC(labTests.getLowerValueOfTC());
        this.setValueOfLDL(labTests.getValueOfLDL());
        this.setUpperValueOfLDL(labTests.getUpperValueOfLDL());
        this.setLowerValueOfLDL(labTests.getLowerValueOfLDL());
        this.setHeartRate(labTests.getHeartRate());
        this.setValueOfHDL(labTests.getValueOfHDL());
        this.setValueOfHB(labTests.getValueOfHB());
        this.setPercentageOfLVEF(labTests.getPercentageOfLVEF());
    }

}
