#Application name
spring:
  application:
    name: insured-member-journey-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health-insurance?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: rg.hibernate.dialect.MySQL8Dialect

#Server Port
server:
  port: 8100

#Swagger related configuration
springdoc:
  swagger-ui:
    path: swagger-ui.html

#Eureka related configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#Spring Actuator related configuration
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - true
    enabled-by-default: true